### ISSUE TITLE
 Pretrained Weights

### ISSUE THREAD

**Issue by noriskinvolved** [rish-av/hsid-cnn#1] opened 2021-12-13 17:27 UTC
Hi,

Thank you for the amazing code!
Can you please upload the pre-trained weights?

**Comment by rish-av** [comment] 2021-12-13 18:06
Can you please send me an email - I will send you the drive link. Cannot make the weights public due to some agreements.

**Comment by rish-av** [comment] 2021-12-21 19:36
Sent and confirmed -- closing the issue.

**Closed as completed** 2021-12-21 19:36 UTC
